### ISSUE TITLE
疫情那个显示的是现有确诊数？能不能添加每天新增数？

### ISSUE THREAD

**Issue by blacknwarrior** [smartmimi/conf#1]

**Comment by smartmimi** [comment]
接口里没有提供新增的数据。
现有确认数，是根据“历史确诊”-“历史治愈”-“历史死亡”来计算出来的。并没有直接提供现有确诊数。
所以也没有每日新增的数据。
如果想提供，那么需要再缓存里保存上一日的最后一次有效数据刷新后的数据，然后根据减法来计算。实现起来有难度，且不太实用。

以前用的腾讯的数据是直接提供计算后的结果的。新换的阿里健康的api的数据就简洁多了，需要自行计算。的确不爽
